package dev.jvault.persistence;

import dev.jvault.outbox.OutboxEntry;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.Instant;
import java.util.List;

/**
 * The parts of persistence that genuinely cannot be written once for PostgreSQL, Microsoft SQL
 * Server and Oracle (decision D5).
 *
 * <p>Deliberately tiny. Everything portable — inserts, updates, reads, the schema's logical shape
 * — lives in shared code. What lands here is the short list of operations whose <em>semantics</em>
 * differ, and the most important of those by a distance is
 * {@link #claimDue(Connection, int, Instant) claiming outbox rows}.
 *
 * <p><strong>Why not an ORM or a query builder.</strong> Either would paper over the dequeue
 * semantics, and the dequeue semantics are the correctness property this system depends on: if
 * two dispatchers can claim one row, jvault writes the same effect to Jira twice. That is the one
 * thing that must be visible in the code rather than generated by a framework.
 */
public interface SqlDialect {

    /** Stable identifier, used to select migrations and to record which dialect is in use. */
    String id();

    /**
     * Atomically takes up to {@code limit} due entries and marks them {@code CLAIMED}, skipping
     * rows another worker already holds.
     *
     * <p>No single statement does this on all three engines:
     *
     * <ul>
     *   <li><strong>PostgreSQL</strong> — {@code ORDER BY … LIMIT … FOR UPDATE SKIP LOCKED} in a
     *       sub-select, with {@code RETURNING} on the outer update.</li>
     *   <li><strong>SQL Server</strong> — a {@code TOP (n) … ORDER BY} CTE with the
     *       {@code UPDLOCK, READPAST} hints, and {@code OUTPUT} instead of {@code RETURNING}.
     *       {@code READPAST} is the skip-locked equivalent.</li>
     *   <li><strong>Oracle</strong> — has {@code FOR UPDATE SKIP LOCKED}, but combining it with a
     *       row-limiting clause raises ORA-02014. The row limit therefore has to come from the
     *       JDBC fetch instead: Oracle locks rows as they are fetched, so reading only the first
     *       n rows locks only those n. Two statements, one transaction.</li>
     * </ul>
     *
     * <p>The caller manages the transaction. The connection must not be in auto-commit.
     */
    List<OutboxEntry> claimDue(Connection connection, int limit, Instant now) throws SQLException;

    /**
     * Whether this exception is the unique constraint firing.
     *
     * <p>Used to make {@code append} idempotent on {@code (ticket_ref, effect_key)} without
     * {@code ON CONFLICT}, {@code MERGE}, or a read-then-write race. JDBC standardises the
     * exception type, so this is mostly portable already — but SQL Server reports duplicate-key
     * through vendor codes that do not always map cleanly, so the dialect gets the final say.
     */
    boolean isUniqueViolation(SQLException e);

    /** Classpath location of this engine's migrations. */
    default String migrationLocation() {
        return "classpath:db/migration/" + id();
    }

    /**
     * Whether this dialect has been exercised against a real database in this repository's tests.
     *
     * <p>An honest flag rather than a comment. A dialect that has only ever been compiled is
     * unverified code, and the deployment check logs a warning when one is selected so nobody
     * discovers it in production (decision D5, "verification burden").
     */
    boolean verifiedByIntegrationTests();
}
